In [3]:
import torch
import torch.nn as nn
from torch.nn import functional as F 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8
batch_size = 4

c:\Users\dogan.irmak\Desktop\my-gpt\cuda\Lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


cpu


In [1]:
with open('fatih_sultan_mehmet.txt','r', encoding='utf-8') as f:
    text = f.read()
print(len(text))
print(text[:200])


627295
Bu kitap beş yüzyıl öncesinden, gerek Eski Kıta'nın ve gerekse
Ortadoğu'nun en güçlü simalarından birinin yaşamını ve gerçek­
leştirdiği işleri genel çizgileriyle ele alarak anlatmaktadır. Otuz yılı
a


In [5]:
with open('fatih_sultan_mehmet.txt','r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
print(chars)
print(len(chars))

['\n', '\x0c', ' ', '!', '"', '%', '&', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '\\', ']', '^', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '~', '£', '\xad', '®', '»', 'Â', 'Ç', 'Î', 'Ö', 'Û', 'Ü', 'â', 'ç', 'î', 'ö', 'û', 'ü', 'Ğ', 'ğ', 'İ', 'ı', 'Ş', 'ş', '‘', '’', '“', '”', '•', '■']
115


In [6]:
string_to_int = { ch:i for i,ch in enumerate(chars) }
int_to_string = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

print(encode('hello'))

[66, 63, 70, 70, 73]


In [7]:
string_to_int = { ch:i for i,ch in enumerate(chars) }
int_to_string = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

encoded_hello = encode('hello')
decoded_hello = decode(encoded_hello)
print(decoded_hello)

hello


In [8]:
string_to_int = { ch:i for i,ch in enumerate(chars) }
int_to_string = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([ 31,  79,   2,  69,  67,  78,  59,  74,   2,  60,  63, 108,   2,  83,
        102,  84,  83, 106,  70,   2, 100,  72,  61,  63,  77,  67,  72,  62,
         63,  72,  11,   2,  65,  63,  76,  63,  69,   2,  34,  77,  69,  67,
          2,  40, 106,  78,  59,   7,  72, 106,  72,   2,  80,  63,   2,  65,
         63,  76,  63,  69,  77,  63,   0,  44,  76,  78,  59,  62,  73, 104,
         79,   7,  72,  79,  72,   2,  63,  72,   2,  65, 102,  98,  70, 102,
          2,  77,  67,  71,  59,  70,  59,  76, 106,  72,  62,  59,  72,   2,
         60,  67])


In [13]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split=='train' else val_data
    ix = torch.randint(len(data)-block_size, (batch_size,))
    print(ix)

    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x.to(device), y.to(device)

x, y = get_batch('train')
print('inputs:')
print(x)
print('targets:')
print(y)

tensor([180789,  19184, 158607, 451033])
inputs:
tensor([[ 80,  59,  76,  62, 106,  13,   2,  31],
        [108,  63,  83,  67,  72,   2,  73,  72],
        [ 76,  59,  62,  59,   2, 100,  72,  63],
        [ 59, 108,  59,  71, 106,  72, 106,  72]])
targets:
tensor([[ 59,  76,  62, 106,  13,   2,  31,  59],
        [ 63,  83,  67,  72,   2,  73,  72,  79],
        [ 59,  62,  59,   2, 100,  72,  63,  71],
        [108,  59,  71, 106,  72, 106,  72,   2]])


In [ ]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size)
        super().__init__(*args, **kwargs)

In [11]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print('when input is', context, 'target is', target)

when input is tensor([31]) target is tensor(79)
when input is tensor([31, 79]) target is tensor(2)
when input is tensor([31, 79,  2]) target is tensor(69)
when input is tensor([31, 79,  2, 69]) target is tensor(67)
when input is tensor([31, 79,  2, 69, 67]) target is tensor(78)
when input is tensor([31, 79,  2, 69, 67, 78]) target is tensor(59)
when input is tensor([31, 79,  2, 69, 67, 78, 59]) target is tensor(74)
when input is tensor([31, 79,  2, 69, 67, 78, 59, 74]) target is tensor(2)


In [ ]:
# predict the next character given a context of 3 characters

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear1 = nn.Linear(embedding_dim, hidden_dim)
        self.linear2 = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        x = F.relu(self.linear1(x))
        x = self.linear2(x)
        return x
    

    def forward(self, x):
        x = self.embedding(x)
        x = F.relu(self.linear1(x))
        x = self.linear2(x)
        return x
    
    def
    